### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by cravay** [ceoy/Nodejs#1]
```
TypeError: Cannot read property 'player1' of undefined
    at getLastPlayerInGame (/home/michael/cardgame/Nodejs/game_server.js:120:33)
    at clean (/home/michael/cardgame/Nodejs/game_server.js:83:19)
    at Socket.<anonymous> (/home/michael/cardgame/Nodejs/game_server.js:74:4)
    at Socket.emit (events.js:95:17)
    at Socket.emit (/home/michael/cardgame/Nodejs/node_modules/socket.io/lib/socket.js:128:10)
    at Socket.onclose (/home/michael/cardgame/Nodejs/node_modules/socket.io/lib/socket.js:425:8)
    at Client.onclose (/home/michael/cardgame/Nodejs/node_modules/socket.io/lib/client.js:232:24)
    at Socket.emit (events.js:117:20)
    at Socket.onClose (/home/michael/cardgame/Nodejs/node_modules/socket.io/node_modules/engine.io/lib/socket.js:304:10)
    at WebSocket.g (events.js:180:16)
```

**Comment by ceoy** [comment]
isch das gsih wo mir ir schuh si gsih?^^

**Comment by ceoy** [comment]
wen 2 spiler imne game glichzitig disconnecte giz gar ke spiler me i dem game^^
-> error.. RIP

**Comment by ceoy** [comment]
okey, auso witeri info:

- fixed
- aber:

![error](https://cloud.githubusercontent.com/assets/14919405/14220715/154c585e-f862-11e5-9298-77831a9fea84.PNG)

d.h. dr spiler wo aktiv isch u wartet muess x games wo ganz (beidi spiler) disconnected worde si dürega..

mi vorschlag (damit i weni z tüe ha huehue): sobaud e spiler use gheit muess er bestätige das er wieder möcht spile

**Comment by cravay** [comment]
passt
